mysql:
  image: mysql:latest
  container_name: mysql-db01
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root1234
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpass
  volumes:
    - ./config/mysql.sh:/root/mysql.sh
    - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf
    - ./data:/var/lib/mysql

phpmyadmin:
  image: registry.iappdragon.com:5000/phpmyadmin:latest
  container_name: myadmin01
  ports:
    - "8080:80"
  links:
    - mysql:db
