mysql:
  image: mysql:latest
  container_name: mysql-db01
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root1234
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpass
  volumes:
    - ./config/login.sh:/root/login.sh
    - ./data:/var/lib/mysql
